Add function to load sharepoint file directly into R
esciencecenter-digital-skills/training-infrastructure pull request #21
Opened 2022-08-03 14:31 UTC by bvreede

This PR adds a function to load the holy excel sheet directly (via a temporary download that gets deleted immediately). The function can be re-used for other documents on Sharepoint (it uses `rio::import` which is flexible and can be used for many different data formats).

The function can be used without arguments to download the file that is (currently) the Holy Excel Sheet. When using the function with arguments to download another file problems can arise: it does not contain any checks to verify that paths exist, or that URLs are correct. This is currently mentioned as TODO, but it could be added if the reviewer so desires 🙃

Check the function with `data <- read_from_drive()`

2022-08-04 08:59 UTC, liekelotte commented
Hi Barbara! Thanks a lot for optimizing this part :) I get the following error when trying to run `read_from_drive`:

```
ds_xlsx <- read_from_drive()

Loading Microsoft Graph login for default tenant
Error in login$get_sharepoint_site(site_url, site_id) : 
  object 'ms_site' not found
```

2022-08-04 09:03 UTC, liekelotte requested changes

2022-08-04 09:03 UTC, liekelotte commented on R/read_from_drive.R
> +  # connect to drive
Hi Barbara! Thanks a lot for optimizing this part :) I get the following error when trying to run `read_from_drive`:

```
ds_xlsx <- read_from_drive()

Loading Microsoft Graph login for default tenant
Error in login$get_sharepoint_site(site_url, site_id) : 
  object 'ms_site' not found
```

ms_site is a Microsoft365R function, so somewhere this is not imported :)

2022-08-04 15:41 UTC, bvreede commented
OK I'm pretty sure I broke all kinds of rules here but.. Can you check if this works now?

```
remotes::install_github(repo = "esciencecenter-digital-skills/training-infrastructure@streamline_microsoft365_use", force=T)
library(traininginfrastructure)
read_from_drive()
```

2022-08-04 18:30 UTC, bvreede commented
Can you check what version of `Microsoft365R` you have?
```
packageVersion("Microsoft365R") 
```

2022-08-05 09:16 UTC, liekelotte commented
> @liekelotte Can you check what version of `Microsoft365R` you have?
> 
> ```
> packageVersion("Microsoft365R") 
> ```

`2.3.0`!

2022-08-05 10:05 UTC, liekelotte commented
> 

this still gives the same error, unfortunately

2022-08-05 10:31 UTC, liekelotte commented
> > @liekelotte Can you check what version of `Microsoft365R` you have?
> > ```
> > packageVersion("Microsoft365R") 
> > ```
> 
> `2.3.0`!

Updating worked :D

2022-08-05 10:37 UTC, bvreede commented
Niiiiiice!
Please let me know if you're OK with this, and then we can merge!

2022-08-05 10:40 UTC, liekelotte approved these changes
Thanks a lot! Really glad we got this fixed :)

2022-08-05 10:40 UTC, liekelotte commented on R/read_from_drive.R
> +  # connect to drive
this is now fixed

2022-08-05 10:41 UTC, merged